version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: doquangbinhminhinternproject
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025"   
      - "1025:1025"

volumes:
  dbdata:
